{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
source:
  git_url: ../

package:
  name: debounce
  version: {{ GIT_VERSION }}

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - pip
    - logging-helpers
    - pycairo-gtk2

  run:
    - pip
    - logging-helpers
    - pycairo-gtk2

test:
  imports:
    - debounce

about:
  home: https://github.com/sci-bots/{{ PKG_NAME }}
  license: BSD
