{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
package:
  name: debounce
  version: {{ GIT_VERSION }}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - pip
    - python >=3.6
    - logging-helpers

test:
  imports:
    - debounce

about:
  home: https://github.com/sci-bots/{{ PKG_NAME }}
  license: BSD
  summary: Python port of lodash.debounce

source:
#  git_url: ../
  path: ..
